# Generated by Django 5.2.7 on 2025-11-25 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Andar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ['andar__numero', 'nome']},
        ),
        migrations.AddField(
            model_name='curso',
            name='alunos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sala',
            name='lugares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sala',
            name='andar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='sala.andar'),
        ),
    ]
