# Generated by Django 5.2.7 on 2025-11-25 04:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0002_andar_alter_sala_options_curso_alunos_sala_lugares_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemestrePeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('periodo', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True, help_text='Indica se este período está ativo')),
            ],
            options={
                'verbose_name': 'Semestre Período',
                'verbose_name_plural': 'Semestres Períodos',
                'ordering': ['-ano', '-periodo'],
                'unique_together': {('ano', 'periodo')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='semestre_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='sala.semestreperiodo'),
        ),
    ]
