# Generated by Django 5.2.7 on 2025-11-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0003_semestreperiodo_curso_semestre_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='metodologia',
            field=models.CharField(choices=[('ativa', 'Metodologia Ativa'), ('tradicional', 'Metodologia Tradicional')], default='tradicional', max_length=15, verbose_name='Metodologia de Ensino'),
        ),
    ]
